### ISSUE TITLE
Production Server

### ISSUE THREAD

**Issue by FumbleBe** [embersds/cityofbrass#3]
Hi guys, I'm trying to start the server under "production" environment, but it's not working very well...

I just put this:

```
ENV RAILS_ENV production
ENV RACK_ENV production
ENV SECRET_KEY_BASE mysuperkey
```
In Dockerfile, (then rebuild), so it start under "production" environment, but it fails...

> cityofbrass_1  | 07:12:39 web.1    | started with pid 6
> cityofbrass_1  | 07:12:39 worker.1 | started with pid 7
> cityofbrass_1  | 07:12:41 web.1    | Puma starting in single mode...
> cityofbrass_1  | 07:12:41 web.1    | * Version 3.10.0 (ruby 2.3.1-p112), codename: Russell's Teapot
> cityofbrass_1  | 07:12:41 web.1    | * Min threads: 16, max threads: 16
> cityofbrass_1  | 07:12:41 web.1    | * Environment: production
> cityofbrass_1  | 07:13:02 worker.1 | 2018-02-13T07:13:02.207Z 7 TID-gpmiazgnk INFO: Running in ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
> cityofbrass_1  | 07:13:02 worker.1 | 2018-02-13T07:13:02.208Z 7 TID-gpmiazgnk INFO: See LICENSE and the LGPL-3.0 for licensing details.
> cityofbrass_1  | 07:13:02 worker.1 | 2018-02-13T07:13:02.208Z 7 TID-gpmiazgnk INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
> cityofbrass_1  | 07:13:02 worker.1 | 2018-02-13T07:13:02.208Z 7 TID-gpmiazgnk INFO: Booting Sidekiq 5.0.4 with redis options {:id=>"Sidekiq-server-PID-7", :url=>nil}
> cityofbrass_1  | 07:13:02 worker.1 | Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:345:in `rescue in establish_connection'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:331:in `establish_connection'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:101:in `block in connect'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:293:in `with_reconnect'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:100:in `connect'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/redis.rb:105:in `connect'
> cityofbrass_1  | 07:13:02 web.1    | * Listening on tcp://0.0.0.0:5000
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:364:in `ensure_connected'
> cityofbrass_1  | 07:13:02 web.1    | Use Ctrl-C to stop
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:221:in `block in process'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:306:in `logging'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:220:in `process'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/redis-3.3.3/lib/redis/client.rb:120:in `call'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/redis.rb:69:in `call'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:251:in `block in info'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:250:in `info'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/sidekiq-5.0.4/lib/sidekiq.rb:113:in `block in redis_info'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/sidekiq-5.0.4/lib/sidekiq.rb:95:in `block in redis'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/sidekiq-5.0.4/lib/sidekiq.rb:92:in `redis'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/sidekiq-5.0.4/lib/sidekiq.rb:106:in `redis_info'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/sidekiq-5.0.4/lib/sidekiq/cli.rb:81:in `run'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/gems/sidekiq-5.0.4/bin/sidekiq:12:in `<top (required)>'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/bin/sidekiq:17:in `load'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bundle/bin/sidekiq:17:in `<top (required)>'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bin/bundle:22:in `load'
> cityofbrass_1  | 07:13:02 worker.1 | /usr/local/bin/bundle:22:in `<main>'
> cityofbrass_1  | 07:13:02 worker.1 | exited with code 1
> cityofbrass_1  | 07:13:02 system   | sending SIGTERM to all processes
> cityofbrass_1  | 07:13:02 web.1    | - Gracefully stopping, waiting for requests to finish
> cityofbrass_1  | 07:13:02 web.1    | === puma shutdown: 2018-02-13 07:13:02 +0000 ===
> cityofbrass_1  | 07:13:02 web.1    | - Goodbye!
> cityofbrass_1  | 07:13:02 web.1    | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
> cityofbrass_1  | 07:13:02 web.1    | SignalException: SIGTERM
> cityofbrass_1  | 07:13:02 web.1    |   /usr/local/bundle/gems/puma-3.10.0/lib/puma/launcher.rb:397:in `block in setup_signals'
> cityofbrass_1  | 07:13:02 web.1    |   /usr/local/bundle/gems/puma-3.10.0/lib/puma/single.rb:106:in `join'
> cityofbrass_1  | 07:13:02 web.1    |   /usr/local/bundle/gems/puma-3.10.0/lib/puma/single.rb:106:in `run'
> cityofbrass_1  | 07:13:02 web.1    |   /usr/local/bundle/gems/puma-3.10.0/lib/puma/launcher.rb:183:in `run'
> cityofbrass_1  | 07:13:02 web.1    |   /usr/local/bundle/gems/puma-3.10.0/lib/puma/cli.rb:77:in `run'
> cityofbrass_1  | 07:13:02 web.1    |   /usr/local/bundle/gems/puma-3.10.0/bin/puma:10:in `<top (required)>'
> cityofbrass_1  | 07:13:02 web.1    |   /usr/local/bundle/bin/puma:17:in `load'
> cityofbrass_1  | 07:13:02 web.1    |   /usr/local/bundle/bin/puma:17:in `<top (required)>'
> cityofbrass_1  | 07:13:02 web.1    | exited with code 1
> cityofbrass_cityofbrass_1 exited with code 1

I 'm really really new to Docker and Ruby... So, sorry if my question is stupid !

Regards

**Comment by embersdev** [comment]
We run City of Brass on Heroku for the production environment.  It uses docker for the development environment and can certainly use it for production, but since i have never deployed docker in production, i wouldn't be much help.

**Comment by FumbleBe** [comment]
It's not a Docker issue, it's a RoR issue, I am just mentioning Docker cause it is where I put my variables to be used by rails as it is docker that start the project. But the problem is the same if you bypass docker. By default, if you start rails server, the app is running under development environment (you have debug messages under the pages, different login screen and stuff). What if I what to start the project under Production? What does it need to run ? What do I have to change ?

thank you !

**Comment by embersdev** [comment]
cityofbrass_1 | 07:13:02 worker.1 | Error connecting to Redis on 127.0.0.1:6379 

It is unable to connect to Redis.

**Comment by FumbleBe** [comment]
Yes, I read that too, but, why is Redis starting when env. is dev. but not when it's production? does that make sense to you ?
